[package]
name = "mactop-rs"
version = "0.1.0"
authors = ["akiozihao <akiozihaoceat@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
psutil = "3.3.0"
ratatui = "0.26.0"
regex = "1.10.5"
